# Default page title
title: Dashbuilder

# Project id name
project: Dashbuilder


encoding: UTF-8
description: Open source dashboards and reporting platform
keywords: open source, software
canonicalBaseUrl: http://www.dashbuilder.org
license: ASL 2.0

asciidoctor:
  :safe: safe
  :attributes:
    imagesdir: ''

profiles:
  development:
    base_url: http://localhost:4242
    developmentMode: true
    
production:
  developmentMode: false
  deploy:
    host: dashbuilder@filemgmt.jboss.org
    path: /www_htdocs/dashbuilder/
    base_url: http://www.dashbuilder.org
